#!/bin/sh

exitCode=0
bold=`tput bold`
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
error=${bold}${red}
success=${bold}${green}
errorBanner="${error}-------------------------------------------------
PRE-PUSH FAILED
-------------------------------------------------${reset}"
successBanner="${success}-------------------------------------------------
PRE-PUSH OK
-------------------------------------------------${reset}"
FAIL=0



echo $'\360\237\217\203 Running javascript linter...'
# commit hook for javascript
npm run lint:js
if [ $? -ne 0 ]; then
    let "FAIL+=1"
fi

echo $'\360\237\217\203 Running style linter...'
# commit hook for styles
npm run lint:css
if [ $? -ne 0 ]; then
    let "FAIL+=1"
fi

echo $'\360\237\217\203 Running tests...'
# Find root of git project
BASEDIR=$(git rev-parse --show-toplevel)
$BASEDIR/node_modules/.bin/mocha
if [ $? -ne 0 ]; then
    let "FAIL+=1"
fi

# Fail if non-zero result
if [[ $FAIL > 0 ]]; then
    echo $'\360\237\230\242 \360\237\221\216'
    echo "${errorBanner}"
    exit 1
else
    echo $'\360\237\230\203 \360\237\215\273 \360\237\215\276'
    echo "${successBanner}"
    exit 0
fi
